Update build-self.yml

diff --git a/.github/workflows/build-self.yml b/.github/workflows/build-self.yml
--- a/.github/workflows/build-self.yml
+++ b/.github/workflows/build-self.yml
@@ -48,34 +48,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           submodules: recursive
-
-      - name: Get tag version
-        run: |
-          # 如果是手动触发 (workflow_dispatch)
-          if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
-            # 获取所有 Tag（确保包含远程 Tag）
-            git fetch --tags
-            # 按版本号排序获取最新 Tag（兼容语义化版本）
-            LATEST_TAG=$(git tag --sort=-v:refname | head -n 1 || echo "nightly")
-
-            # 去掉 Tag 名称中的 'v' 前缀
-            # VERSION="${LATEST_TAG}"
-          else
-           # 原有逻辑：从推送的 Tag 中提取版本号
-           TAG_VERSION="${GITHUB_REF##*/}"
-           # VERSION="${TAG_VERSION}"
-          fi
-
-          # 处理无 Tag 的情况（可选：报错或默认值）
-          if [ -z "$VERSION" ]; then
-            echo "::error::No valid tag found!"
-            VERSION="0.0.0"
-          fi
-
-          # 将信息写入环境变量
-          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
-
+          
       - name: Setup Android Signing
         if: startsWith(matrix.platform,'android')
         run: |
@@ -141,7 +114,33 @@ jobs:
           for file in $(find . -type f -not -name "*.sha256"); do
             sha256sum "$file" > "${file}.sha256"
           done  
-      
+
+      - name: Get tag version
+        run: |
+          # 如果是手动触发 (workflow_dispatch)
+          if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
+            # 获取所有 Tag（确保包含远程 Tag）
+            git fetch --tags
+            # 按版本号排序获取最新 Tag（兼容语义化版本）
+            LATEST_TAG=$(git tag --sort=-v:refname | head -n 1 || echo "nightly")
+
+            # 去掉 Tag 名称中的 'v' 前缀
+            VERSION="${LATEST_TAG}"
+          else
+           # 原有逻辑：从推送的 Tag 中提取版本号
+           TAG_VERSION="${GITHUB_REF##*/}"
+           VERSION="${TAG_VERSION}"
+          fi
+
+          # 处理无 Tag 的情况（可选：报错或默认值）
+          if [ -z "$VERSION" ]; then
+            echo "::error::No valid tag found!"
+            VERSION="0.0.0"
+          fi
+
+          # 将信息写入环境变量
+          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
+          # echo "VERSION=$VERSION" >> $GITHUB_ENV
 
       - name: Release
         if: ${{ env.IS_STABLE == 'true' }}
